"""
NDMA incident report model.

Maps to: ndma_reports

Stores the JSON payload generated by the EOC CommandPage after a drill
or real event, matching the NDMA SIH reporting schema.
"""

import uuid
from datetime import datetime

from sqlalchemy import String, Integer, JSON, TIMESTAMP
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class NDMAReport(Base):
    """
    An NDMA-format incident report generated by an EOC operator.

    The ``payload`` JSONB field holds the full NDMA SIH report body
    (drill session details, participant counts, evacuation times, etc.).
    """

    __tablename__ = "ndma_reports"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    drill_session_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    institution_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    report_type: Mapped[str] = mapped_column(String(50), nullable=False)
    # Full NDMA SIH report body — arbitrary JSON so the schema can evolve
    payload: Mapped[dict] = mapped_column(JSON, default=dict)
    # Human-readable status
    status: Mapped[str] = mapped_column(String(50), default="draft")
    created_by: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), default=datetime.utcnow
    )
