"""
NDMA incident report API — powers the EOC "Generate NDMA Report" button.

Provides:

- POST /api/v1/reports/ndma
    Accept a JSON report payload (typically harvested from a drill session
    and the analytics endpoint) and persist it as an NDMA-format report.

- GET /api/v1/reports/ndma
    List reports for a given institution, most-recent first.

The report payload shape mirrors the NDMA SIH reporting requirements:
drill metadata, participant counts, evacuation times, compliance scores, etc.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Annotated

from pydantic import BaseModel, Field
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db_session
from app.models.report import NDMAReport

logger = logging.getLogger(__name__)

router = APIRouter()


class NDMAReportCreate(BaseModel):
    """Body of POST /api/v1/reports/ndma."""

    title: str = Field(..., max_length=255)
    drill_session_id: str | None = Field(None, max_length=255)
    institution_id: str | None = Field(None, max_length=255)
    report_type: str = Field("DRILL_INCIDENT", max_length=50)
    payload: dict = Field(default_factory=dict)
    created_by: str | None = Field(None, max_length=255)


class NDMAReportResponse(BaseModel):
    """A stored NDMA report."""

    id: str
    title: str
    drill_session_id: str | None
    institution_id: str | None
    report_type: str
    status: str
    created_by: str | None
    created_at: datetime
    payload: dict


@router.post(
    "/reports/ndma",
    response_model=NDMAReportResponse,
    tags=["reports"],
    summary="Generate an NDMA-format incident report",
)
async def create_ndma_report(
    body: NDMAReportCreate,
    db: AsyncSession = Depends(get_db_session),
) -> NDMAReportResponse:
    """
    Persist an NDMA-format report generated by the EOC operator.

    The CommandPage's "Generate NDMA Report" button should POST the current
    drill session data (participant counts, evacuation times, analytics KPIs)
    as the ``payload`` field so the report survives beyond the browser session.

    Returns the created report with its server-assigned UUID.
    """
    drill_uuid: uuid.UUID | None = None
    inst_uuid: uuid.UUID | None = None

    if body.drill_session_id:
        try:
            drill_uuid = uuid.UUID(body.drill_session_id)
        except ValueError:
            raise HTTPException(status_code=422, detail="drill_session_id must be a valid UUID")

    if body.institution_id:
        try:
            inst_uuid = uuid.UUID(body.institution_id)
        except ValueError:
            raise HTTPException(status_code=422, detail="institution_id must be a valid UUID")

    report = NDMAReport(
        title=body.title,
        drill_session_id=drill_uuid,
        institution_id=inst_uuid,
        report_type=body.report_type,
        payload=body.payload,
        status="generated",
        created_by=body.created_by,
    )
    db.add(report)
    await db.commit()
    await db.refresh(report)

    logger.info(
        "Created NDMA report id=%s title=%r type=%s",
        report.id, report.title, report.report_type,
    )

    return NDMAReportResponse(
        id=str(report.id),
        title=report.title,
        drill_session_id=str(report.drill_session_id) if report.drill_session_id else None,
        institution_id=str(report.institution_id) if report.institution_id else None,
        report_type=report.report_type,
        status=report.status,
        created_by=report.created_by,
        created_at=report.created_at,
        payload=report.payload,
    )


@router.get(
    "/reports/ndma",
    response_model=list[NDMAReportResponse],
    tags=["reports"],
    summary="List NDMA reports",
)
async def list_ndma_reports(
    db: AsyncSession = Depends(get_db_session),
    institution_id: Annotated[str | None, Query(description="Filter by institution UUID")] = None,
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
) -> list[NDMAReportResponse]:
    """
    Return NDMA reports, most-recent first.

    Optionally filter by ``institution_id``.  The ``limit`` parameter caps
    the number of rows returned to bound query time on large tables.
    """
    q = select(NDMAReport).order_by(NDMAReport.created_at.desc()).limit(limit)
    if institution_id:
        try:
            inst_uuid = uuid.UUID(institution_id)
            q = q.where(NDMAReport.institution_id == inst_uuid)
        except ValueError:
            raise HTTPException(status_code=422, detail="institution_id must be a valid UUID")

    result = await db.execute(q)
    reports = result.scalars().all()

    return [
        NDMAReportResponse(
            id=str(r.id),
            title=r.title,
            drill_session_id=str(r.drill_session_id) if r.drill_session_id else None,
            institution_id=str(r.institution_id) if r.institution_id else None,
            report_type=r.report_type,
            status=r.status,
            created_by=r.created_by,
            created_at=r.created_at,
            payload=r.payload,
        )
        for r in reports
    ]
