"""add user_profiles and ndma_reports tables

- user_profiles: extended cadet/warden/admin profile fields (avatar, badges,
  training progress, emergency contacts) that don't belong in the auth table.
- ndma_reports: NDMA-format incident reports generated by the EOC.

Revision ID: 3a8f4b91c2d7
Revises: f2e91c83a4b5
Create Date: 2026-09-07 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3a8f4b91c2d7"
down_revision: Union[str, None] = "f2e91c83a4b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS user_profiles (
            user_id UUID PRIMARY KEY,
            avatar_seed VARCHAR(100),
            avatar_image_url VARCHAR(2048),
            rank VARCHAR(50),
            squad VARCHAR(50),
            training_level INTEGER NOT NULL DEFAULT 1,
            drills_completed INTEGER NOT NULL DEFAULT 0,
            total_score INTEGER NOT NULL DEFAULT 0,
            badges JSONB NOT NULL DEFAULT '[]'::jsonb,
            preferred_language VARCHAR(10),
            emergency_contact_name VARCHAR(255),
            emergency_contact_phone VARCHAR(20),
            medical_notes VARCHAR(2000),
            extra JSONB NOT NULL DEFAULT '{}'::jsonb,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS ndma_reports (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            title VARCHAR(255) NOT NULL,
            drill_session_id UUID,
            institution_id UUID,
            report_type VARCHAR(50) NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            status VARCHAR(50) NOT NULL DEFAULT 'draft',
            created_by VARCHAR(255),
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
        )
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_user_profiles_updated_at
            ON user_profiles (updated_at DESC)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_ndma_reports_institution
            ON ndma_reports (institution_id)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_ndma_reports_drill_session
            ON ndma_reports (drill_session_id)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_ndma_reports_created_at
            ON ndma_reports (created_at DESC)
    """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_ndma_reports_created_at")
    op.execute("DROP INDEX IF EXISTS idx_ndma_reports_drill_session")
    op.execute("DROP INDEX IF EXISTS idx_ndma_reports_institution")
    op.execute("DROP TABLE IF EXISTS ndma_reports")
    op.execute("DROP INDEX IF EXISTS idx_user_profiles_updated_at")
    op.execute("DROP TABLE IF EXISTS user_profiles")
